### ISSUE TITLE
channel tree scrollbar changes position unecessarily

### ISSUE THREAD

**Issue by hxe** [hexchat/hexchat#1382]
HexChat 2.10.2 x64 on Windows 7. can confirm this happens on x86 and on Windows 8 too though

i'm in enough channels that my channel tree has a scrollbar. whenever i use ctrl+pgup or ctrl+pgdn to change channels the scrollbar drastically changes its position to somewhere i dont want it to go and it makes it very annoying. same thing happens when switching contexts with a script. for some reason hexchat refreshes the entire channel list and goes to a position which it thinks is correct but is not the desired (previous) position. its understandable for the scrollbar to shift a bit if switching to a channel which is currently off the screen. but it changes position even when switching to channels which are already on screen. this is new behaviour which wasnt present in hexchat in older versions im pretty sure.

**Comment by TingPing** [comment]
If behavior changed its entirely in gtk.

**Comment by hxe** [comment]
does that mean disabling the gtk theme should fix it? ive tried hexchat with and without the gtk theme

**Comment by TingPing** [comment]
No. Gtk is the entire UI of hexchat, you can't remove it.

**Comment by jwshields** [comment]
I'm having the same issue. Windows 8.1 X64, Hexchat 2.10.2
I also think this may be tangibly related to issue 1179

Steps:
- have enough servers/channels to cause hexchat to use a scrollbar, at least 2x the size of the screen (I have 15 networks & 150 channels)
- use Ctrl+PgUp/Ctrl+PgDn to navigate through

My scrollbar will wildly move, going back up to the top of the list, then scrolling back down & settling on the channel that I just scrolled to.

**Comment by jwshields** [comment]
This is still happening. Can confirm on Windows 10 (multiple dev builds) & Hexchat versions up to 2.12.3

**Comment by hxe** [comment]
same. 
HexChat 2.12.3, x64, Windows 10
