### ISSUE TITLE
"No ping reply" with Hexchat 2.12.2/2.12.3

### ISSUE THREAD

**Issue by Chway** [hexchat/hexchat#1866]
I keep being disconnected with the last version (2.12.3) with the message "No ping reply for 67s" sometimes with much bigger numbers (+600s), on every servers I join.
When I connect to my bouncer, I can stay connected for hours, then I'm  disconnected with the message "No ping reply for 19000s".
I don't have any issue with the version 2.12.2 or any other applications.

The only messages I can find in the "Raw Log" related to the pings requests are:

```
<< PING LAG1021068503
>> :barjavel.freenode.net PONG barjavel.freenode.net :LAG1021068503
<< PING LAG1021098503
>> :barjavel.freenode.net PONG barjavel.freenode.net :LAG1021098503
...
```
Hexchat: 2.12.3
OS: WIndows 10 (14393.351)

**Comment by TingPing** [comment]
> I don't have any issue with the version 2.12.2 or any other applications.

Surely that version behaves the exact same as nothing changed between those two releases.

**Comment by paladox** [comment]
I am too getting disconnected from my bouncer, it seems when I go into the background, ie open another application and leve hexchat in the background, I go back and realise that I have no irc notifications and then I do a whois call and it disconnects me and reconnects me.

This has happen recently so either hexchat 2.12.2 or 2.12.3.

I doint get ping timeout, I get  Disconnected.

**Comment by paladox** [comment]
Also his problem seems related to this https://github.com/hexchat/hexchat/commit/e7101ebcae9ab846faa19511d374cd331f5ce684 change in hexchat 2.12.3.

**Comment by paladox** [comment]
Maybe this https://github.com/hexchat/hexchat/commit/6b2cc1d28b67dd352c4be775ba214ca864cc5500 too?

https://github.com/hexchat/hexchat/commit/a970c1ae2ef89ae691fc2104db0c2c4e512f58f3

**Comment by Chway** [comment]
I can finally reproduce this issue over and over again!

I don't have any problem when I start HexChat and autoconnect to multiple servers, HexChat can ping every servers correctly but as soon as I connect to a new one, there is no more ping activities on any servers I'm on. Then after few minutes, I join a new server again, few seconds later I'm disconnected from every servers.

Here's a classic raw log:

```
<< PING LAG1347603503   <<<< startup
>> :irc.rizon.no PONG irc.rizon.no :LAG1347603503
<< PING LAG1347633503
>> :irc.rizon.no PONG irc.rizon.no :LAG1347633503
<< PING LAG1347663503
>> :irc.rizon.no PONG irc.rizon.no :LAG1347663503   <<<< I joined a new server here
>> PING :irc.rizon.no
<< PONG :irc.rizon.no
```

You were right, this problem happen on both versions, 2.12.2 and 2.12.3, no problem with the 2.12.1.

**Comment by paladox** [comment]
It may be caused by https://github.com/hexchat/hexchat/commit/6b2cc1d28b67dd352c4be775ba214ca864cc5500

**Comment by paladox** [comment]
Going back to hexchat 2.12.1 fixes the problem for me, so the bug exist somewhere in hexchat 2.12.2 and 2.12.3. But my theory is the problem started in one of those ^^ patches.

Since power saving though it is good, it can have other affects too so we should keep power saving under an option.

**Comment by paladox** [comment]
Switching off lag meter and throttle meter seems to work too tested upgrading to hexchat 2.12.3 and switched those off and it seems to work.

go to preference -> user list and the under extra gadgets select the drop downs and click off then save and restart hexchat.

**Comment by TingPing** [comment]
> Since power saving though it is good, it can have other affects too so we should keep power saving under an option.

Just fyi, the power saving aspect of that change probably isn't really relevant and there is probably just  a mistake in logic if anything.

**Comment by paladox** [comment]
Oh ok.

**Comment by Chway** [comment]
@paladox Sadly that doesn't solve my problem, same as before, HexChat stop to ping my servers as soon as I join a new one.

**Comment by paladox** [comment]
Oh, It fixed my problem with it keeps disconnecting me from irc everytime I leave it in the background.

**Comment by TingPing** [comment]
> everytime I leave it in the background.

Somebody else mentioned the same behavior, it doesn't make much sense and doesn't happen on Linux. Will have to investigate if GLib is doing something stupid.

**Comment by paladox** [comment]
Oh, I'm using windows 10 insider build 14965.

**Comment by paladox** [comment]
After a few hours of using the workaround it dosent work any more. So the other workaround is to use hexchat 2.12.1.

**Comment by anowlcalledjosh** [comment]
This is happening to me too -- I keep getting disconnected from all servers I'm connected to. I'm on Ubuntu 16.04, HexChat version 2.12.3 (from [overcoder's PPA](https://launchpad.net/~overcoder/+archive/ubuntu/hexchat)).

**Comment by Chway** [comment]
I'm curious, anyone have been able to reproduce my problem by following the steps [mentioned here](https://github.com/hexchat/hexchat/issues/1866#issuecomment-259950974) ?

**Comment by TingPing** [comment]
@Chway I connect to multiple servers every day without issue.

**Comment by anowlcalledjosh** [comment]
@Chway: seems like you're right, I left HexChat open for a day with no/few issues, then I manually joined a server a few minutes ago, and a couple of minutes after that, suddenly disconnected from every server.

**Comment by paladox** [comment]
@TingPing hi, do you connect to znc? Could be an issue when connecting to a znc as I have downgraded to hexchat 2.12.1 and it has worked for me, as soon as I upgrade to 2.12.3 then it stops working properly.

**Comment by TingPing** [comment]
I connect to 2 networks with ZNC and 1 network directly.

**Comment by paladox** [comment]
Oh, @TingPing try going idle for 10-30 mins on it, ie put hexchat in the background for 10-30mins then go back, and try a whois call on someone.

**Comment by TingPing** [comment]
I run my client 24/7. I have only gotten a ping timeout like once since release and I think it was a valid one. I do get disconnected from time to time but it is hard for me to relate it to this as my router has actually been crashing lately.

**Comment by d601** [comment]
This is happening to me too. I'm on 2.12.3 and Windows 10. I'm connected to two servers directly and one through ZNC, and as soon as I connect to a new server, all my other connections drop with a message like "No ping reply for 172209 seconds, disconnecting."

**Comment by tomek** [comment]
Plase check build 3118df2 from here: https://dl.hexchat.net/hexchat/testing/

**Comment by paladox** [comment]
Thanks.

**Comment by paladox** [comment]
Currently it is working fine, but I doint want to say it is fixed just incase it isen't. But currently it is working.

**Comment by paladox** [comment]
May want to release a 2.12.3.1 release?

**Comment by TingPing** [comment]
I'll throw out a release soon if everybody here says it fixed it.

**Comment by Chway** [comment]
Yes, that resolve my problem, I can now join a server at any time without issues. Thank you!

**Comment by paladox** [comment]
@TingPing after having it in the background for an hour it worked when I got into it so looks like you fixed it :)

**Comment by d601** [comment]
That fixed it for me too.

**Comment by TingPing** [comment]
Thanks, I'll close this as fixed and probably make a release this weekend.

**Comment by paladox** [comment]
Thanks

**Comment by paladox** [comment]
Hi, I found sometimes being idle to long and someone pings you, it wont notify you, the problem is fixed where it keeps disconnecting you, but when I go into the application I find I was pinged but the application did not flash to tell me that.

**Comment by jwshields** [comment]
I'm running Windows 10 1607.14393.351
I was running 2.12.2, upgraded to 2.12.3, found the timeout problems, went back to 2.12.2. Got the notification that .4 was available, upgraded to that, and I am still experiencing ping timeouts. It appears to be only on my larger networks (30+ channels)

**Comment by meganleighwoulffe** [comment]
So, I know this is closed, but I just upgraded to 2.12.4 on Windows 10 using a portable install. The error in the server log is 'No ping reply for XX seconds, disconnecting'. The time is anywhere between 40 and 70 seconds each time. This happens after I connect to a single server and autojoin my channels. I have trying turning off away tracking. This is still an issue for me. I'll be installing 2.12.1 until I hear back.

**Comment by ZweisteinT** [comment]
got the same problem as meganleighwoulffe. Timeout every 80 seconds... guess i have to search for an alternative client.

**Comment by utrott** [comment]
+1 for new release, tried to verify with 99e16110bc42856492636b4b492a0cffe6d70a88 but did not run, seems the test builds are currently nonfunctional

**Comment by tomek** [comment]
@utrott I tested new test build and it worked just fine, I compiled new build myself - they should be virtually the same (only difference is that my build is signed) - you can get it here: https://dl.hexchat.net/hexchat/testing/

**Comment by utrott** [comment]
I have downloaded again from: https://dl.hexchat.net/hexchat/testing/master/99e16110bc42856492636b4b492a0cffe6d70a88/HexChat%202.12.4%20x64.exe

It does start and immediately crashes again, with: 

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	hexchat.exe
  Anwendungsversion:	2.12.4.0
  Anwendungszeitstempel:	594985ac
  Fehlermodulname:	hexchat.exe
  Fehlermodulversion:	2.12.4.0
  Fehlermodulzeitstempel:	594985ac
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	0000000000027fa6
  Betriebsystemversion:	6.1.7601.2.1.0.256.4
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	1d49
  Zusatzinformation 2:	1d491da159d989b6061ac716425b371e
  Zusatzinformation 3:	734b
  Zusatzinformation 4:	734b405cc77ac73e65d351d8768b8149

Sorry abaout the names, this is a german win7.
