### ISSUE TITLE
Nick permission list not updating when services ops with Inspircd 3.0

### ISSUE THREAD

**Issue by adamus1red** [hexchat/hexchat#2335]
When joining a channel on a server running Inspircd 3 I need to run `/names` to manually update nicklist to show any permission change. This occurs when the any user joins the channel.

**Comment by TingPing** [comment]
What does *Window > Raw Log* look like when you join and run `/names`.

**Comment by adamus1red** [comment]
UI does not update the nick list with the op until the manual `/names` done at `@time=2019-05-06T15:07:57.000Z`

```<< JOIN #test 
>> @time=2019-05-06T15:07:29.000Z :Guest3!~a@testnet-qs3.dod.0sg3ho.IP PART :#test
>> @time=2019-05-06T15:07:29.000Z :Guest3!~a@testnet-qs3.dod.0sg3ho.IP JOIN #test * :realname
<< MODE #test
<< WHO #test %chtsunfra,152
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 332 Guest3 #test :Feel free to test any bots, scripts, etc in this channel.
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 333 Guest3 #test admin :1403572744
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 353 Guest3 = #test :Guest3 @God @^Quark^
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 366 Guest3 #test :End of /NAMES list.
>> @time=2019-05-06T15:07:29.000Z :God!God@the.all.mighty.one NOTICE Guest3 :[#test] Welcome to #test. Feel free to test any bots, scripts, etc in this channel.
>> @time=2019-05-06T15:07:29.000Z :God!God@the.all.mighty.one MODE #test +o :Guest3
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 324 Guest3 #test :+Pnt
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 329 Guest3 #test :1403572555
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 354 Guest3 152 #test ~a testnet-qs3.dod.0sg3ho.IP irc.deb1.lan Guest3 H@s 0 :realname
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 354 Guest3 152 #test God the.all.mighty.one irc.deb1.lan God H@ 0 :Also known as Satan
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 354 Guest3 152 #test ~quantum quark.lan irc.deb1.lan ^Quark^ H@s ^Quark^ :Quarkly
>> @time=2019-05-06T15:07:29.000Z :irc.deb1.lan 315 Guest3 #test :End of /WHO list.
<< PING LAG2327093070
>> @time=2019-05-06T15:07:32.000Z :irc.deb1.lan PONG irc.deb1.lan :LAG2327093070
<< NAMES #test
>> @time=2019-05-06T15:07:57.000Z :irc.deb1.lan 353 Guest3 = #test :@Guest3 @God @^Quark^
>> @time=2019-05-06T15:07:57.000Z :irc.deb1.lan 366 Guest3 #test :End of /NAMES list.
<< WHO #test %chtsunfra,152
<< PING LAG2327123071
>> @time=2019-05-06T15:08:02.000Z :irc.deb1.lan 354 Guest3 152 #test ~a testnet-qs3.dod.0sg3ho.IP irc.deb1.lan Guest3 H@s 0 :realname
>> @time=2019-05-06T15:08:02.000Z :irc.deb1.lan 354 Guest3 152 #test God the.all.mighty.one irc.deb1.lan God H@ 0 :Also known as Satan
>> @time=2019-05-06T15:08:02.000Z :irc.deb1.lan 354 Guest3 152 #test ~quantum quark.lan irc.deb1.lan ^Quark^ H@s ^Quark^ :Quarkly
>> @time=2019-05-06T15:08:02.000Z :irc.deb1.lan 315 Guest3 #test :End of /WHO list.
>> @time=2019-05-06T15:08:02.000Z :irc.deb1.lan PONG irc.deb1.lan :LAG2327123071
<< PING LAG2327153071
```

**Comment by TingPing** [comment]
This was fixed by https://github.com/hexchat/hexchat/pull/2301 then.

**Comment by SaberUK** [comment]
Has there been a release since that PR was merged? If not, would it be possible for you to make one so that users stop encountering this bug? Thanks.

**Comment by adamus1red** [comment]
There hasn't been a release including #2301

**Comment by sebastiannielsen** [comment]
@SadieCat A release implementing this fix has still not been pushed.
Latest release is: 2019-11-14 acccording to Windows Store.

**Comment by SadieCat** [comment]
I don't know if the Windows store version was updated but this is fixed in HexChat 2.14.3.

**Comment by sebastiannielsen** [comment]
Version published in Windows Store is 2.14.2 so @TingPing needs to push the update to WStore.
