### ISSUE TITLE
Issue with dead key input using us-international keyboard layout.

### ISSUE THREAD

**Issue by Stefan-v-Oudenaarden** [hexchat/hexchat#37]
For more information on the us-international keyboard layout: http://en.wikipedia.org/wiki/Keyboard_layout#US-International

When trying to input single or double quotation marks the result does not match the expected result, the expected result would be ' and " but instead  I get ´ and ¨ 

This bug has been around for a while in xchat-wdk and now hexchat but I've never seen it on the official xchat build. 

For reference: 

Windows 7 SP1, 64 bit.

About Dialog 

HexChat 2.9.1

A multiplatform IRC Client

OS: Windows 7 [3,50GHz]
Charset: CP1252 GTK+: 2.16.6
XChat Revision: r1521
Compiled: Jul 27 2012
Portable Mode: No
Build Type: x64

**Comment by rimas-kudelis** [comment]
For the reference, this is the upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=569581.

**Comment by Neurodynasoft** [comment]
Hmmm I am running 2.12.4 (which according to hexchat is the current version) and this is still a problem. In Win10, US International keyboard:

1. Pressing  ' + SPACE gives ´ instead of '
2. Pressing " + SPACE gives ¨ instead of "
3. Typing can't gives can instead of can't
4. Typing possessives 's gives ś instead

The 3rd one is really frustrating because i keep typing can't, and instead my sentences show can. 

So I don't see how this issue has been resolved yet.

**Comment by TingPing** [comment]
@Neurodynasoft That is a discussion to have with Gtk.

**Comment by rimas-kudelis** [comment]
@TingPing no, this was fixed after 2.24.31. In case you're building against GTK+ from MSYS2/MINGW, this has been taken care of already: https://github.com/Alexpux/MINGW-packages/pull/1979 . Otherwise, you may want to take a look there.

**Comment by Pieter12345** [comment]
@rimas-kudelis This issue has been closed and stated to be fixed a long time ago now. I've just installed HexChat (32 and 64 bits version) in portable mode on Windows 7 64 bits and I'm getting ´ instead of ' and ¨ instead of ". Changing my "Input methods" (right click chat input field) to any given option does not fix this issue. My keyboard language is set to "United States (International)" on a Dutch OS.

As I understand, this might be caused by an issue outside of HexChat. Nevertheless, this causes a bug in HexChat. So in order to provide properly working software, this (maybe exceptional) case should at least be detected and give feedback to the end-user or (preferably) have some custom handling that ensures expected behaviour.

Besides these design choices, is there anything I can do to fix this bug on my system?

**Comment by Neurodynasoft** [comment]
@Pieter12345 Yes, the issue still persists, which is a shame.

I was able to workaround it using this: https://github.com/Xesyto/Hexchat-DeadKeyFix

You need python to be installed in your system to use it. Hope it helps.

**Comment by rimas-kudelis** [comment]
Note that the version where I said this was fixed is a GTK+ version, and not a Hexchat version. It's up to Hexchat developers/packagers to package their Windows installers with updated GTK+, and I'm not one of them.
Also, this ticket was closed because Hexchat couldn't fix it on their side long before I posted my comment.

By the way, unless you're making use of the "International" features (specifically, dead keys) in the US (International) keyboard layout, you could just switch to generic US layout. I'm saying this because I've seen a few cases where people used the International layout without actually realising what it's meant for and that they didn't need it.

**Comment by TingPing** [comment]
The current Windows release of HexChat uses Gtk 2.24.31 btw (which was the latest at release time I believe).
